### PR TITLE
Snapshot download retry

### LINKED ISSUE #162: Docker Device Agent failed to pull snapshot after restart
### Current Behavior

After a nightly restart of the Device Agent running on Docker, the process of getting the snapshot timed out.

Annotation-Annotation on 2023-08-21 at 16-20-14 png

### Expected Behavior

The Device agent should keep retrying the snapshot download if the prior attempt timed out.

### Steps To Reproduce

The network this device is running on is believed to have restarted at the same time as the device agent.

### Environment

- FlowForge version: FF Cloud 1.10.2
- Node.js version: 16.20.2
- npm version:
- Platform/OS:
- Browser:

### PR DESCRIPTION
**Pull request by Steve-Mcl**
close #162 

## Description

Performs retries on failed snapshot downloads.

In line with internal discussions, this is the retry schedule:

TRY # | INTERVAL | JITTER
------| -------- | ------
1     | immediate| 0      (1st attempt, not a retry)
2     | 1s       | ± 5s   (2nd attempt, 1st retry) - quick to act, but reasonable amount of jitter (effectively somewhere between 1s~6s)
3     | 20s      | ± 10s
4     | 40s      | ± 20s
5     | 1m       | ± 30s
6     | 5m       | ± 30s
n...  | 5m       | ± 30s

This has been thoroughly tested locally using [wondershaper](https://manpages.ubuntu.com/manpages/trusty/man8/wondershaper.8.html) to limit bandwidth. 

Additionally, tests have been added to ensure the `IntervalJitter` class performs as expected.  

This should go some way to alleviate contention when a mass deploy / mass restart of devices occurs.

Demo resutlts for reference...

`## ℹ️ NOTE: set network bandwidth to ~100kbps at this point`
```
[AGENT] 06/09/2023 12:59:58 [info] Agent starting...
[AGENT] 6 Sept 2023, 12:59:58 info: Web UI Server now listening at http://127.0.0.1:1871/
[AGENT] 06/09/2023 12:59:58 [info] Version: 1.11.0
[AGENT] 06/09/2023 12:59:58 [info] Mode: Device Mode
[AGENT] 06/09/2023 12:59:58 [info] Device: 1qb0X87bWD
[AGENT] 06/09/2023 12:59:58 [info] ForgeURL: https://forge.flowforge.dev/
[AGENT] 06/09/2023 12:59:58 [info] Configuration :-
[AGENT] 06/09/2023 12:59:58 [info]   * Instance           : 2977c8e6-4f53-4e5b-8321-0a9cafab865f
[AGENT] 06/09/2023 12:59:58 [info]   * Snapshot           : L2E9BJl9rY
[AGENT] 06/09/2023 12:59:58 [info]   * Settings           : d9c388ceda545f2d7ab7fd95e90d1cc322b43e722f97314e7443747a9d20b960
[AGENT] 06/09/2023 12:59:58 [info]   * Operation Mode     : autonomous
[AGENT] 06/09/2023 12:59:58 [info]   * Licensed           : yes
[AGENT] 06/09/2023 12:59:58 [info] Environment :-
[AGENT] 06/09/2023 12:59:58 [info]   * FF_DEVICE_ID       : 1qb0X87bWD
[AGENT] 06/09/2023 12:59:58 [info]   * FF_DEVICE_NAME     : jammy35-device-1
[AGENT] 06/09/2023 12:59:58 [info]   * FF_DEVICE_TYPE     : 
[AGENT] 06/09/2023 12:59:58 [info]   * FF_SNAPSHOT_ID     : L2E9BJl9rY
[AGENT] 06/09/2023 12:59:58 [info]   * FF_SNAPSHOT_NAME   : V2-1MB
[AGENT] 06/09/2023 12:59:58 [info] Starting MQTT heartbeat thread. Interval: 30s (±5s)
[AGENT] 06/09/2023 12:59:59 [info] MQTT connected
[AGENT] 06/09/2023 12:59:59 [info] New snapshot available
[AGENT] 06/09/2023 13:01:02 [warn] Problem getting snapshot: TimeoutError: Timeout awaiting 'request' for 30000ms

  ## ℹ️ NOTE ☝️: GOT does (by default) 2 retries hence the delay of 1min until retry #1 👇

[AGENT] 06/09/2023 13:01:07 [info] Update state retry attempt #1  ## ℹ️ Occurred within ~5s of first fail
[AGENT] 06/09/2023 13:01:07 [info] New snapshot available
[AGENT] 06/09/2023 13:02:31 [info] Update state retry attempt #2  ## ℹ️ Occurred within ~24s of previous retry fail (remember, GOT does 2 retries itself)
[AGENT] 06/09/2023 13:02:31 [info] New snapshot available[AGENT] 06/09/2023 13:04:18 [info] Update state retry attempt #3 
 ## ℹ️ Occurred within ~47s of previous retry fail (remember, GOT does 2 retries itself)
[AGENT] 06/09/2023 13:04:18 [info] New snapshot available

  ## ℹ️ NOTE: ramped up network bandwidth to ~5mbps at this point 👈

[AGENT] 06/09/2023 13:04:30 [info] Launching with new settings...
[AGENT] 06/09/2023 13:04:30 [info] Configuration :-
[AGENT] 06/09/2023 13:04:30 [info]   * Instance           : 2977c8e6-4f53-4e5b-8321-0a9cafab865f
[AGENT] 06/09/2023 13:04:30 [info]   * Snapshot           : j1EPrlzQXz
[AGENT] 06/09/2023 13:04:30 [info]   * Settings           : d9c388ceda545f2d7ab7fd95e90d1cc322b43e722f97314e7443747a9d20b960
[AGENT] 06/09/2023 13:04:30 [info]   * Operation Mode     : autonomous
[AGENT] 06/09/2023 13:04:30 [info]   * Licensed           : yes
[AGENT] 06/09/2023 13:04:30 [info] Environment :-
[AGENT] 06/09/2023 13:04:30 [info]   * FF_DEVICE_ID       : 1qb0X87bWD
[AGENT] 06/09/2023 13:04:30 [info]   * FF_DEVICE_NAME     : jammy35-device-1
[AGENT] 06/09/2023 13:04:30 [info]   * FF_DEVICE_TYPE     : 
[AGENT] 06/09/2023 13:04:30 [info]   * FF_SNAPSHOT_ID     : j1EPrlzQXz
[AGENT] 06/09/2023 13:04:30 [info]   * FF_SNAPSHOT_NAME   : v1-3MB
[AGENT] 06/09/2023 13:04:30 [info] Updating configuration files
[AGENT] 06/09/2023 13:04:30 [info] Installing dependencies
[AGENT] 06/09/2023 13:04:44 [info] Updating theme files
[AGENT] 06/09/2023 13:04:44 [info] Starting Node-RED
[NR] 06/09/2023 13:04:49 [info] 

Welcome to Node-RED
===================
```

## Related Issue(s)

#162, #165 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [x] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

File: lib/IntervalJitter.js [hunk 1]
```diff
@@ -70,31 +142,67 @@ class IntervalJitter extends EventEmitter {
...
+        self.lastTime = Date.now()
+        if (typeof callback === 'function') { self.callback = callback }
+        self.emit('internal:start1', self.firstInterval, self.firstJitter)
     }
 
     /** Stop the interval timer */
     stop () {
         this.#stopped = true
-        clearInterval(this.#jitterTimer)
+        debug('⏲️ STOP INTERVAL TIMER')
```
Comment (Steve-Mcl) [inline lib/IntervalJitter.js:205]:
```suggestion
        debug('Interval Timer Stop requested')
```

File: lib/IntervalJitter.js [hunk 2]
```diff
@@ -1,65 +1,137 @@
...
                     const now = Date.now()
-                    self.callback && self.callback.call(this, now - self.lastTime)
-                    self.emit('interval', now - self.lastTime)
-                    self.lastTime = now
-                }, variance)
-            }, interval)
+                    try {
+                        self.#executing = true
+                        self.#counter++
+                        const msSinceLastCall = now - self.lastTime
```
Comment (Steve-Mcl) [inline lib/IntervalJitter.js:92]:
```suggestion
                        const msSinceLastCall = now - self.lastTime
                        debug('Interval Timer Executing')
```

File: lib/IntervalJitter.js [hunk 3]
```diff
@@ -1,65 +1,137 @@
...
-            self.#initTimer = setTimeout(() => {
+            const variance = IntervalJitter.calculateJitter(jitter)
+            const firstDelay = interval + variance
+            self.#initTimer = setTimeout(async () => {
+                if (self.#stopped) { return }
+                const now = Date.now()
+                try {
+                    self.#executing = true
+                    self.#counter++
+                    const msSinceLastCall = now - self.lastTime
```
Comment (Steve-Mcl) [inline lib/IntervalJitter.js:62]:
```suggestion
                    const msSinceLastCall = now - self.lastTime
                    debug('Interval Timer Executing')
```

**Review by knolleary — APPROVED** [review]
