### PR TITLE
Remove/recreate symlink to module_cache if exists

### LINKED ISSUE #62: Restarting NR with module_cache failing as symlink already present
### Current Behavior

If you change the snapshot or the settings for a device after the initial snapshot has been deployed to a device it fails because the symlink is already present:

```
[AGENT] Mar 30, 2023, 10:48:08 AM info: FlowForge Device Agent
[AGENT] Mar 30, 2023, 10:48:08 AM info: ----------------------
[AGENT] Mar 30, 2023, 10:48:08 AM info: Agent starting...
[AGENT] Mar 30, 2023, 10:48:08 AM info: Version: 0.6.1
[AGENT] Mar 30, 2023, 10:48:08 AM info: Mode: Device Mode
[AGENT] Mar 30, 2023, 10:48:08 AM info: Device: QjBy25x8Kl
[AGENT] Mar 30, 2023, 10:48:08 AM info: ForgeURL: https://forge.flowforge.dev
[AGENT] Mar 30, 2023, 10:48:08 AM info: Starting MQTT heartbeat thread. Interval: 30s (±5s)
[AGENT] Mar 30, 2023, 10:48:15 AM info: New snapshot available
[AGENT] Mar 30, 2023, 10:48:15 AM info: Instance: 4337da71-6cb6-44c8-8d84-5f1a27b20142
[AGENT] Mar 30, 2023, 10:48:15 AM info: Snapshot: DxEPk5LQvK
[AGENT] Mar 30, 2023, 10:48:15 AM info: Settings: none
[AGENT] Mar 30, 2023, 10:48:15 AM info: Updating configuration files
[AGENT] Mar 30, 2023, 10:48:15 AM info: Installing dependencies
[AGENT] Mar 30, 2023, 10:48:15 AM info: Starting Node-RED
[NR] 30 Mar 10:48:15 - [info] 
[NR] Welcome to Node-RED
[NR] ===================
[NR] 30 Mar 10:48:15 - [info] Node-RED version: v3.0.2
[NR] 30 Mar 10:48:15 - [info] Node.js  version: v16.19.1
[NR] 30 Mar 10:48:15 - [info] Linux 6.2.7-100.fc36.x86_64 x64 LE
[NR] 30 Mar 10:48:15 - [info] Loading palette nodes
[NR] 30 Mar 10:48:16 - [warn] ------------------------------------------------------
[NR] 30 Mar 10:48:16 - [warn] [@flowforge/nr-file-nodes/file] Error: FlowForge file nodes cannot be loaded without required settings (line:28)
[NR] 30 Mar 10:48:16 - [warn] ------------------------------------------------------
[NR] 30 Mar 10:48:16 - [info] Settings file  : /opt/flowforge-device/project/settings.js
[NR] 30 Mar 10:48:16 - [info] Context store  : 'memory' [module=memory]
[NR] 30 Mar 10:48:16 - [info] Context store  : 'persistent' [module=localfilesystem]
[NR] 30 Mar 10:48:16 - [info] User directory : /opt/flowforge-device/project
[NR] 30 Mar 10:48:16 - [warn] Projects disabled : set editorTheme.projects.enabled=true to enable
[NR] 30 Mar 10:48:16 - [info] Flows file     : /opt/flowforge-device/project/flows.json
[NR] 30 Mar 10:48:16 - [info] Admin UI disabled
[NR] 30 Mar 10:48:16 - [info] Server now running at http://127.0.0.1:1880
[NR] 30 Mar 10:48:16 - [warn] Encrypted credentials not found
[NR] 30 Mar 10:48:16 - [info] Starting flows
[NR] 30 Mar 10:48:16 - [info] Started flows
[NR] 30 Mar 10:48:31 - [info] [debug:debug 1] 1680173311339
[NR] 30 Mar 10:48:46 - [info] [debug:debug 1] 1680173326352
[AGENT] Mar 30, 2023, 10:48:46 AM info: New settings available
[AGENT] Mar 30, 2023, 10:48:46 AM info: Stopping current snapshot
[AGENT] Mar 30, 2023, 10:48:46 AM info: Stopping Node-RED
[NR] 30 Mar 10:48:46 - [info] Stopping flows
[NR] 30 Mar 10:48:46 - [info] Stopped flows
[AGENT] Mar 30, 2023, 10:48:46 AM info: Stopped Node-RED
[AGENT] Mar 30, 2023, 10:48:46 AM info: Instance: 4337da71-6cb6-44c8-8d84-5f1a27b20142
[AGENT] Mar 30, 2023, 10:48:46 AM info: Snapshot: DxEPk5LQvK
[AGENT] Mar 30, 2023, 10:48:46 AM info: Settings: b4ee8fb3a93c8b5f854dda9b716bf4451bea85ecde42d4df4851b8b15890cd94
[AGENT] Mar 30, 2023, 10:48:46 AM info: Updating configuration files
[AGENT] Mar 30, 2023, 10:48:46 AM info: Installing dependencies
[AGENT] Mar 30, 2023, 10:48:46 AM warn: Error whilst starting Node-RED: Error: EEXIST: file already exists, symlink '/opt/flowforge-device/module_cache/node_modules' -> '/opt/flowforge-device/project/node_modules'
[AGENT] Mar 30, 2023, 10:48:46 AM info: Stopping Node-RED
[AGENT] Mar 30, 2023, 10:48:46 AM info: Cleaning instance directory
```

### Expected Behavior

If the symlink already exsists and points to the right place ignore, or delete and recreate it.

### Steps To Reproduce

- add `moduleCache: true` to device.yml
- populate `/opt/flowforge-device-agent/module_cache` with package.json from snapshot
- run `npm install` in `/opt/flowforge-device-agent/module_cache`
- start agent
- change snapshot or settings assigned to the device

### Environment

- FlowForge version: 1.5.0+git
- Node.js version: 16.x
- npm version: 8.x
- Platform/OS: kube/linux (staging)
- Browser: NA

device agent 0.6.1

### PR DESCRIPTION
**Pull request by hardillb**
## Description

If using the moduleCache:true option, then restarts fail because the symlink already exists. This change removes the link if it already exists and recreates it

## Related Issue(s)

fixes #62

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [x] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

File: lib/launcher.js [hunk 1]
```diff
@@ -55,13 +55,20 @@ class Launcher {
...
             try {
                 await fs.access(sourceDir)
             } catch (ee) {
                 return Promise.reject(ee)
             }
-            return fs.symlink(sourceDir, path.join(this.projectDir, 'node_modules'), 'dir')
+
+            if (existsSync(targetDir)) {
+                await fs.unlink(targetDir)
+            }
```
Comment (knolleary) [inline lib/launcher.js:69]:
```suggestion
            if (existsSync(targetDir)) {
                await fs.rm(targetDir, { force: true, recursive: true })
            }
```
If `node_modules` exists and is a real directory, `unlink` will throw an error. That is a very possible scenario if the user enables the module cache after running with it.

**Review by knolleary — APPROVED** [review]
