### PR TITLE
Fix crash on startup

### LINKED ISSUE #134: Fails to start with a fresh var directory
### Current Behavior

```
$ flowforge-device-agent -d ./var -c ./var/device.yml
[AGENT] 6 Jul 2023, 12:38:50 info: FlowForge Device Agent
[AGENT] 6 Jul 2023, 12:38:50 info: ----------------------
[AGENT] 06/07/2023 12:38:50 [info] Agent starting...
[AGENT] 06/07/2023 12:38:50 [info] Version: 1.9.3
[AGENT] 06/07/2023 12:38:50 [info] Mode: Device Mode
[AGENT] 06/07/2023 12:38:50 [info] Device: QjBy25x8Kl
[AGENT] 06/07/2023 12:38:50 [info] ForgeURL: https://forge.flowforge.dev
[AGENT] 06/07/2023 12:38:50 [info] Starting MQTT heartbeat thread. Interval: 30s (±5s)
[Error: ENOENT: no such file or directory, open '/home/hardillb/temp/device/var/project/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/hardillb/temp/device/var/project/package.json'
}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open '/home/hardillb/temp/device/var/project/flows.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/hardillb/temp/device/var/project/flows.json'
}

Node.js v18.16.0
```

### Expected Behavior

Not crash on startup

### Steps To Reproduce

just start device agent without any existing project

### Environment

- FlowForge device agent version: 1.9.3
- Node.js version: 18.x
- npm version: 9.x
- Platform/OS: Linux
- Browser: na

### PR DESCRIPTION
**Pull request by hardillb**
fixes #134

## Description

Crash on startup is no project/flows.json or project/package.json

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/flowforge/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

File: lib/launcher.js [hunk 1]
```diff
@@ -117,8 +117,12 @@ class Launcher {
...
     async readFlow () {
         debug(`Reading flows file: ${this.files.flows}`)
-        const flows = await fs.readFile(this.files.flows, 'utf8')
-        return JSON.parse(flows)
+        try {
+          const flows = await fs.readFile(this.files.flows, 'utf8')
+          return JSON.parse(flows)
+        } catch (error) {
+            console.error(error)
+        }
```
Comment (Steve-Mcl) [inline lib/launcher.js:125]:
```suggestion
        try {
            const flows = await fs.readFile(this.files.flows, 'utf8')
            return JSON.parse(flows)
        } catch (error) {
            console.error(error)
        }
```

fix linting

**Review by Steve-Mcl — APPROVED** [review]
